### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by musicm122** [petebacondarwin/ng1-component-router-demo#7]
Win10 64bit
node version is 5.5.0
lite-server is 2.1.0

Ello, I ran 
npm install 
then npm start
and on npm start got the following.

```
λ npm start

> component-router-angular-1@1.0.0 start C:\Users\terra\Documents\GitHub\ng1-component-router-demo
> lite-server

Did not detect a `bs-config.json` or `bs-config.js` override file. Using lite-server defaults...
** browser-sync options **
{ injectChanges: false,
  files: [ './**/*.{html,htm,css,js}' ],
  server: { baseDir: './', middleware: [ [Function], [Function] ] } }
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://10.164.161.47:3002
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://10.164.161.47:3001
 --------------------------------------
[BS] Serving files from: ./
[BS] Watching files...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3001
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1236:14)
    at listen (net.js:1272:10)
    at Server.listen (net.js:1368:5)
    at Object.module.exports.startServer [as fn] (C:\Users\terra\Documents\GitHub\ng1-component-router-demo\node_modules\browser-sync-ui\lib\async.js:116:39)
    at C:\Users\terra\Documents\GitHub\ng1-component-router-demo\node_modules\browser-sync-ui\lib\UI.js:184:14
    at iterate (C:\Users\terra\Documents\GitHub\ng1-component-router-demo\node_modules\async-each-series\index.js:8:5)
    at C:\Users\terra\Documents\GitHub\ng1-component-router-demo\node_modules\async-each-series\index.js:16:16
    at C:\Users\terra\Documents\GitHub\ng1-component-router-demo\node_modules\browser-sync-ui\lib\UI.js:192:13

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! component-router-angular-1@1.0.0 start: `lite-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the component-router-angular-1@1.0.0 start script 'lite-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the component-router-angular-1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lite-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls component-router-angular-1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\terra\Documents\GitHub\ng1-component-router-demo\npm-debug.log
```

**Comment by musicm122** [comment]
I'm an idiot that did not read the docs.

> HEADS UP The current version of the router on npm does not work with this demo. You need to use the file that is currently in this repository under the /node_modules/@angular/router/angular1/angular_1_router.js path. So be careful when you run the install that it doesn't overwrite this file.

**Comment by musicm122** [comment]
NM still an issue
